import type { Command } from 'commander'
import fs from 'node:fs'
import path from 'node:path'
import prompts from 'prompts'
import { THEME_TEMPLATES } from '../templates/themes'
import { findConfig, readConfig, writeConfig } from '../utils/config'
import { header, newLine, styles } from '../utils/prompts'

const BUILT_IN_THEMES = [
  { name: 'stellar', description: 'Default cosmic theme' },
  { name: 'sirius', description: 'Bright and energetic' },
  { name: 'polaris', description: 'Cool and professional' },
  { name: 'antares', description: 'Warm and bold' },
  { name: 'vega', description: 'Clean and minimal' },
  { name: 'aldebaran', description: 'Rich and sophisticated' },
] as const

type BuiltInThemeName = (typeof BUILT_IN_THEMES)[number]['name']

const THEME_PRIMARY_COLORS: Record<BuiltInThemeName, string> = {
  stellar: 'oklch(55% 0.187 285)',
  sirius: 'oklch(60% 0.2 200)',
  polaris: 'oklch(55% 0.18 240)',
  antares: 'oklch(58% 0.19 30)',
  vega: 'oklch(50% 0.15 160)',
  aldebaran: 'oklch(52% 0.18 300)',
}

const BORDER_RADIUS_OPTIONS = [
  { title: 'none (0)', value: '0' },
  { title: 'sm (0.25rem)', value: '0.25rem' },
  { title: 'md (0.375rem)', value: '0.375rem' },
  { title: 'lg (0.5rem)', value: '0.5rem' },
  { title: 'xl (0.75rem)', value: '0.75rem' },
  { title: 'full (9999px)', value: '9999px' },
]

/**
 * Generate CSS custom properties for a custom theme.
 */
export function generateThemeCss(
  themeName: string,
  baseTheme: string,
  primaryColor: string,
  borderRadius: string,
): string {
  return `/* Stellar UI - Custom Theme: ${themeName} */
/* Based on: ${baseTheme} */
/* Generated by @stellar-vue-ui/cli */

:root {
  /* Colors - Primary */
  --stellar-primary: ${primaryColor};
  --stellar-primary-foreground: oklch(98% 0.01 285);

  /* Colors - Secondary */
  --stellar-secondary: oklch(94% 0.02 285);
  --stellar-secondary-foreground: oklch(18% 0.03 285);

  /* Colors - Muted */
  --stellar-muted: oklch(95% 0.01 285);
  --stellar-muted-foreground: oklch(42% 0.02 285);

  /* Colors - Accent */
  --stellar-accent: oklch(93% 0.04 285);
  --stellar-accent-foreground: oklch(18% 0.03 285);

  /* Colors - Destructive */
  --stellar-destructive: oklch(50% 0.2 27);
  --stellar-destructive-foreground: oklch(98% 0 0);

  /* Colors - Background & Foreground */
  --stellar-background: oklch(100% 0 0);
  --stellar-foreground: oklch(12% 0.03 285);

  /* Colors - Card */
  --stellar-card: oklch(99% 0.005 285);
  --stellar-card-foreground: oklch(12% 0.03 285);

  /* Colors - Popover */
  --stellar-popover: oklch(99% 0.005 285);
  --stellar-popover-foreground: oklch(12% 0.03 285);

  /* Colors - Border, Input, Ring */
  --stellar-border: oklch(91% 0.01 285);
  --stellar-input: oklch(91% 0.01 285);
  --stellar-ring: ${primaryColor};

  /* Border Radius */
  --stellar-radius: ${borderRadius};
}

.dark {
  --stellar-background: oklch(12% 0.03 285);
  --stellar-foreground: oklch(98% 0.01 285);
  --stellar-primary: ${primaryColor};
  --stellar-primary-foreground: oklch(98% 0.01 285);
  --stellar-secondary: oklch(20% 0.03 285);
  --stellar-secondary-foreground: oklch(98% 0.01 285);
  --stellar-muted: oklch(20% 0.02 285);
  --stellar-muted-foreground: oklch(65% 0.02 285);
  --stellar-accent: oklch(22% 0.04 285);
  --stellar-accent-foreground: oklch(98% 0.01 285);
  --stellar-destructive: oklch(40% 0.18 27);
  --stellar-destructive-foreground: oklch(98% 0 0);
  --stellar-border: oklch(25% 0.02 285);
  --stellar-input: oklch(25% 0.02 285);
  --stellar-ring: ${primaryColor};
  --stellar-card: oklch(14% 0.03 285);
  --stellar-card-foreground: oklch(98% 0.01 285);
  --stellar-popover: oklch(14% 0.03 285);
  --stellar-popover-foreground: oklch(98% 0.01 285);
}
`
}

/**
 * Generate JSON representation of a theme.
 */
export function generateThemeJson(
  themeName: string,
  baseTheme: string,
  primaryColor: string,
  borderRadius: string,
): string {
  const tokens = {
    name: themeName,
    base: baseTheme,
    colors: {
      'primary': primaryColor,
      'primary-foreground': 'oklch(98% 0.01 285)',
      'secondary': 'oklch(94% 0.02 285)',
      'secondary-foreground': 'oklch(18% 0.03 285)',
      'muted': 'oklch(95% 0.01 285)',
      'muted-foreground': 'oklch(42% 0.02 285)',
      'accent': 'oklch(93% 0.04 285)',
      'accent-foreground': 'oklch(18% 0.03 285)',
      'destructive': 'oklch(50% 0.2 27)',
      'destructive-foreground': 'oklch(98% 0 0)',
      'background': 'oklch(100% 0 0)',
      'foreground': 'oklch(12% 0.03 285)',
      'card': 'oklch(99% 0.005 285)',
      'card-foreground': 'oklch(12% 0.03 285)',
      'popover': 'oklch(99% 0.005 285)',
      'popover-foreground': 'oklch(12% 0.03 285)',
      'border': 'oklch(91% 0.01 285)',
      'input': 'oklch(91% 0.01 285)',
      'ring': primaryColor,
    },
    borderRadius,
  }
  return JSON.stringify(tokens, null, 2)
}

/**
 * Generate Tailwind config snippet for a theme.
 */
export function generateThemeTailwind(
  themeName: string,
  primaryColor: string,
  borderRadius: string,
): string {
  return `// Stellar UI - Theme: ${themeName}
// Add this to your tailwind.config.ts
const ${themeName}Theme = {
  extend: {
    colors: {
      stellar: {
        primary: 'var(--stellar-primary)',
        'primary-foreground': 'var(--stellar-primary-foreground)',
        secondary: 'var(--stellar-secondary)',
        'secondary-foreground': 'var(--stellar-secondary-foreground)',
        muted: 'var(--stellar-muted)',
        'muted-foreground': 'var(--stellar-muted-foreground)',
        accent: 'var(--stellar-accent)',
        'accent-foreground': 'var(--stellar-accent-foreground)',
        destructive: 'var(--stellar-destructive)',
        'destructive-foreground': 'var(--stellar-destructive-foreground)',
        background: 'var(--stellar-background)',
        foreground: 'var(--stellar-foreground)',
        card: 'var(--stellar-card)',
        'card-foreground': 'var(--stellar-card-foreground)',
        popover: 'var(--stellar-popover)',
        'popover-foreground': 'var(--stellar-popover-foreground)',
        border: 'var(--stellar-border)',
        input: 'var(--stellar-input)',
        ring: 'var(--stellar-ring)',
      },
    },
    borderRadius: {
      stellar: 'var(--stellar-radius)', // ${borderRadius}
    },
    // Primary color value: ${primaryColor}
  },
}

export default ${themeName}Theme
`
}

async function themeCreateAction(options: { yes?: boolean, cwd?: string }): Promise<void> {
  const cwd = path.resolve(options.cwd ?? process.cwd())

  header('Stellar UI - Create Custom Theme')

  let themeName: string
  let baseTheme: BuiltInThemeName
  let primaryColor: string
  let borderRadius: string

  if (options.yes) {
    themeName = 'my-theme'
    baseTheme = 'stellar'
    primaryColor = THEME_PRIMARY_COLORS.stellar
    borderRadius = '0.5rem'
  }
  else {
    const response = await prompts([
      {
        type: 'text',
        name: 'themeName',
        message: 'Theme name',
        initial: 'my-theme',
        validate: (value: string) => (value.trim().length > 0 ? true : 'Theme name is required'),
      },
      {
        type: 'select',
        name: 'baseTheme',
        message: 'Base theme',
        choices: BUILT_IN_THEMES.map(t => ({
          title: `${t.name} — ${t.description}`,
          value: t.name,
        })),
        initial: 0,
      },
      {
        type: 'text',
        name: 'primaryColor',
        message: 'Primary color',
        initial: (prev: BuiltInThemeName) =>
          THEME_PRIMARY_COLORS[prev] ?? THEME_PRIMARY_COLORS.stellar,
      },
      {
        type: 'select',
        name: 'borderRadius',
        message: 'Border radius',
        choices: BORDER_RADIUS_OPTIONS,
        initial: 3, // lg = 0.5rem
      },
    ])

    if (response.themeName === undefined || response.baseTheme === undefined) {
      console.log(styles.info('Theme creation cancelled.'))
      return
    }

    themeName = response.themeName as string
    baseTheme = response.baseTheme as BuiltInThemeName
    primaryColor = (response.primaryColor as string) ?? THEME_PRIMARY_COLORS[baseTheme]
    borderRadius = (response.borderRadius as string) ?? '0.5rem'
  }

  const cssContent = generateThemeCss(themeName, baseTheme, primaryColor, borderRadius)

  const themesDir = path.join(cwd, 'themes')
  if (!fs.existsSync(themesDir)) {
    fs.mkdirSync(themesDir, { recursive: true })
  }

  const themeFile = path.join(themesDir, `${themeName}.css`)
  fs.writeFileSync(themeFile, cssContent, 'utf-8')

  newLine()
  console.log(styles.success(`Theme "${themeName}" created at themes/${themeName}.css`))
  console.log(styles.dim(`  Base: ${baseTheme}`))
  console.log(styles.dim(`  Primary: ${primaryColor}`))
  console.log(styles.dim(`  Border radius: ${borderRadius}`))
  newLine()
}

async function themeListAction(): Promise<void> {
  header('Stellar UI - Available Themes')

  console.log(styles.highlight('Built-in themes:'))
  newLine()

  for (const theme of BUILT_IN_THEMES) {
    console.log(`  ${styles.title(theme.name.padEnd(14))} ${styles.dim(theme.description)}`)
  }

  // Check for custom themes in the project
  const cwd = process.cwd()
  const themesDir = path.join(cwd, 'themes')

  if (fs.existsSync(themesDir)) {
    const files = fs.readdirSync(themesDir).filter(f => f.endsWith('.css'))
    if (files.length > 0) {
      newLine()
      console.log(styles.highlight('Custom themes:'))
      newLine()
      for (const file of files) {
        const name = file.replace(/\.css$/, '')
        console.log(`  ${styles.title(name.padEnd(14))} ${styles.dim('Custom theme')}`)
      }
    }
  }

  newLine()
}

async function themeApplyAction(name: string, options: { cwd?: string }): Promise<void> {
  const cwd = path.resolve(options.cwd ?? process.cwd())

  const config = await readConfig(cwd)
  if (!config) {
    console.log(styles.error('No Stellar UI config found. Run `stellar-ui init` first.'))
    process.exitCode = 1
    return
  }

  // Validate the theme name
  const builtInNames = BUILT_IN_THEMES.map(t => t.name)
  const themesDir = path.join(cwd, 'themes')
  const customThemes: string[] = fs.existsSync(themesDir)
    ? fs
        .readdirSync(themesDir)
        .filter(f => f.endsWith('.css'))
        .map(f => f.replace(/\.css$/, ''))
    : []

  const allThemes = [...builtInNames, ...customThemes]
  if (!allThemes.includes(name)) {
    console.log(styles.error(`Unknown theme: "${name}". Available themes: ${allThemes.join(', ')}`))
    process.exitCode = 1
    return
  }

  // Write theme CSS to the variables file
  const cssPath = path.join(cwd, config.cssVariables)
  const isBuiltIn = builtInNames.includes(name)

  if (isBuiltIn) {
    const themeCSS = THEME_TEMPLATES[name]
    if (!themeCSS) {
      console.log(styles.error(`Theme template "${name}" not found.`))
      process.exitCode = 1
      return
    }
    const cssDir = path.dirname(cssPath)
    if (!fs.existsSync(cssDir)) {
      fs.mkdirSync(cssDir, { recursive: true })
    }
    fs.writeFileSync(cssPath, themeCSS, 'utf-8')
  }
  else {
    // Custom theme — copy from themes/ directory
    const customCssPath = path.join(themesDir, `${name}.css`)
    const cssDir = path.dirname(cssPath)
    if (!fs.existsSync(cssDir)) {
      fs.mkdirSync(cssDir, { recursive: true })
    }
    fs.copyFileSync(customCssPath, cssPath)
  }

  // Update config with the new theme reference
  const updatedConfig = {
    ...config,
    theme: name,
  } as typeof config & { theme: string }

  const configDir = await findConfig(cwd)
  if (!configDir) {
    console.log(styles.error('Could not find config directory.'))
    process.exitCode = 1
    return
  }

  await writeConfig(updatedConfig as typeof config, configDir)

  console.log(styles.success(`Theme "${name}" applied to your project.`))
  console.log(styles.dim(`  CSS variables written to ${config.cssVariables}`))
  newLine()
}

async function themeExportAction(name: string, options: { format?: string }): Promise<void> {
  const format = options.format ?? 'css'

  // Validate format
  if (!['css', 'json', 'tailwind'].includes(format)) {
    console.log(styles.error(`Unknown format: "${format}". Use: css, json, or tailwind`))
    process.exitCode = 1
    return
  }

  // Find theme data
  const builtInTheme = BUILT_IN_THEMES.find(t => t.name === name)
  if (!builtInTheme) {
    // Check for custom theme file
    const cwd = process.cwd()
    const themeFile = path.join(cwd, 'themes', `${name}.css`)
    if (!fs.existsSync(themeFile)) {
      console.log(
        styles.error(
          `Unknown theme: "${name}". Use \`stellar-ui theme list\` to see available themes.`,
        ),
      )
      process.exitCode = 1
      return
    }
    // For custom themes, just output the CSS file content for css format
    if (format === 'css') {
      console.log(fs.readFileSync(themeFile, 'utf-8'))
      return
    }
  }

  // Use default values for the built-in theme export
  const primaryColor
    = THEME_PRIMARY_COLORS[name as BuiltInThemeName] ?? THEME_PRIMARY_COLORS.stellar
  const borderRadius = '0.5rem'

  let output: string

  switch (format) {
    case 'json':
      output = generateThemeJson(name, name, primaryColor, borderRadius)
      break
    case 'tailwind':
      output = generateThemeTailwind(name, primaryColor, borderRadius)
      break
    case 'css':
    default:
      output = generateThemeCss(name, name, primaryColor, borderRadius)
      break
  }

  console.log(output)
}

export function registerThemeCommand(program: Command): void {
  const theme = program.command('theme').description('Manage themes')

  theme
    .command('create')
    .description('Create a custom theme')
    .option('-y, --yes', 'Use defaults')
    .option('--cwd <cwd>', 'Working directory', process.cwd())
    .action(themeCreateAction)

  theme.command('list').description('List available themes').action(themeListAction)

  theme
    .command('apply <name>')
    .description('Apply a theme to your project')
    .option('--cwd <cwd>', 'Working directory', process.cwd())
    .action(themeApplyAction)

  theme
    .command('export <name>')
    .description('Export a theme')
    .option('-f, --format <format>', 'Output format: css, json, or tailwind', 'css')
    .action(themeExportAction)
}
