import type { ThemePalette } from '@stellar-vue-ui/theme'
import type { Command } from 'commander'
import fs from 'node:fs'
import path from 'node:path'
import { deriveTokensFromPalette } from '@stellar-vue-ui/theme'
import prompts from 'prompts'
import { THEME_TEMPLATES } from '../templates/themes'
import { findConfig, readConfig, writeConfig } from '../utils/config'
import { header, newLine, styles } from '../utils/prompts'

const BUILT_IN_THEMES = [
  { name: 'stellar', description: 'Default cosmic theme' },
  { name: 'sirius', description: 'Bright and energetic' },
  { name: 'polaris', description: 'Cool and professional' },
  { name: 'antares', description: 'Warm and bold' },
  { name: 'vega', description: 'Clean and minimal' },
  { name: 'aldebaran', description: 'Rich and sophisticated' },
] as const

const BORDER_RADIUS_OPTIONS = [
  { title: 'none (0)', value: '0' },
  { title: 'sm (0.25rem)', value: '0.25rem' },
  { title: 'md (0.375rem)', value: '0.375rem' },
  { title: 'lg (0.5rem)', value: '0.5rem' },
  { title: 'xl (0.75rem)', value: '0.75rem' },
  { title: 'full (9999px)', value: '9999px' },
]

const HEX_RE = /^#[0-9a-f]{3,6}$/i

function validateHex(value: string): boolean | string {
  return HEX_RE.test(value.trim()) ? true : 'Enter a valid hex color (e.g. #667eea)'
}

/**
 * Format a ThemeColors token map as CSS custom properties with --stellar- prefix.
 */
function formatTokensAsCss(
  tokens: ReturnType<typeof deriveTokensFromPalette>,
  borderRadius: string,
): string {
  return `  /* Colors - Primary */
  --stellar-primary: ${tokens.primary.DEFAULT};
  --stellar-primary-foreground: ${tokens.primary.foreground};
  --stellar-primary-focus: ${tokens.primaryFocus};

  /* Colors - Secondary */
  --stellar-secondary: ${tokens.secondary.DEFAULT};
  --stellar-secondary-foreground: ${tokens.secondary.foreground};

  /* Colors - Accent */
  --stellar-accent: ${tokens.accent.DEFAULT};
  --stellar-accent-foreground: ${tokens.accent.foreground};

  /* Colors - Muted */
  --stellar-muted: ${tokens.muted.DEFAULT};
  --stellar-muted-foreground: ${tokens.muted.foreground};

  /* Colors - Destructive */
  --stellar-destructive: ${tokens.destructive.DEFAULT};
  --stellar-destructive-foreground: ${tokens.destructive.foreground};

  /* Colors - Error */
  --stellar-error: ${tokens.error.DEFAULT};
  --stellar-error-foreground: ${tokens.error.foreground};
  --stellar-error-focus: ${tokens.errorFocus};

  /* Colors - Success */
  --stellar-success: ${tokens.success.DEFAULT};
  --stellar-success-foreground: ${tokens.success.foreground};
  --stellar-success-focus: ${tokens.successFocus};

  /* Colors - Warning */
  --stellar-warning: ${tokens.warning.DEFAULT};
  --stellar-warning-foreground: ${tokens.warning.foreground};
  --stellar-warning-focus: ${tokens.warningFocus};

  /* Colors - Info */
  --stellar-info: ${tokens.info.DEFAULT};
  --stellar-info-foreground: ${tokens.info.foreground};
  --stellar-info-focus: ${tokens.infoFocus};

  /* Colors - Background & Foreground */
  --stellar-background: ${tokens.background};
  --stellar-foreground: ${tokens.foreground};

  /* Colors - Card */
  --stellar-card: ${tokens.card.DEFAULT};
  --stellar-card-foreground: ${tokens.card.foreground};

  /* Colors - Popover */
  --stellar-popover: ${tokens.popover.DEFAULT};
  --stellar-popover-foreground: ${tokens.popover.foreground};

  /* Colors - Border, Input, Ring */
  --stellar-border: ${tokens.border};
  --stellar-input: ${tokens.input};
  --stellar-ring: ${tokens.ring};

  /* Border Radius */
  --stellar-radius: ${borderRadius};`
}

/**
 * Generate CSS custom properties for a custom theme from a palette.
 */
export function generateThemeCss(
  themeName: string,
  palette: ThemePalette,
  borderRadius: string,
): string {
  const lightTokens = deriveTokensFromPalette(palette, 'light')
  const darkTokens = deriveTokensFromPalette(palette, 'dark')

  return `/* Stellar UI - Custom Theme: ${themeName} */
/* Generated by @stellar-vue-ui/cli */

:root {
${formatTokensAsCss(lightTokens, borderRadius)}
}

.dark {
${formatTokensAsCss(darkTokens, borderRadius)}
}
`
}

/**
 * Generate JSON representation of a theme from a palette.
 */
export function generateThemeJson(
  themeName: string,
  palette: ThemePalette,
  borderRadius: string,
): string {
  const tokens = deriveTokensFromPalette(palette, 'light')

  const colorMap: Record<string, string> = {
    'primary': tokens.primary.DEFAULT,
    'primary-foreground': tokens.primary.foreground,
    'secondary': tokens.secondary.DEFAULT,
    'secondary-foreground': tokens.secondary.foreground,
    'muted': tokens.muted.DEFAULT,
    'muted-foreground': tokens.muted.foreground,
    'accent': tokens.accent.DEFAULT,
    'accent-foreground': tokens.accent.foreground,
    'destructive': tokens.destructive.DEFAULT,
    'destructive-foreground': tokens.destructive.foreground,
    'background': tokens.background,
    'foreground': tokens.foreground,
    'card': tokens.card.DEFAULT,
    'card-foreground': tokens.card.foreground,
    'popover': tokens.popover.DEFAULT,
    'popover-foreground': tokens.popover.foreground,
    'border': tokens.border,
    'input': tokens.input,
    'ring': tokens.ring,
  }

  const result = {
    name: themeName,
    palette,
    colors: colorMap,
    borderRadius,
  }
  return JSON.stringify(result, null, 2)
}

/**
 * Generate Tailwind config snippet for a theme.
 */
export function generateThemeTailwind(themeName: string, borderRadius: string): string {
  return `// Stellar UI - Theme: ${themeName}
// Add this to your tailwind.config.ts
const ${themeName}Theme = {
  extend: {
    colors: {
      stellar: {
        primary: 'var(--stellar-primary)',
        'primary-foreground': 'var(--stellar-primary-foreground)',
        secondary: 'var(--stellar-secondary)',
        'secondary-foreground': 'var(--stellar-secondary-foreground)',
        muted: 'var(--stellar-muted)',
        'muted-foreground': 'var(--stellar-muted-foreground)',
        accent: 'var(--stellar-accent)',
        'accent-foreground': 'var(--stellar-accent-foreground)',
        destructive: 'var(--stellar-destructive)',
        'destructive-foreground': 'var(--stellar-destructive-foreground)',
        background: 'var(--stellar-background)',
        foreground: 'var(--stellar-foreground)',
        card: 'var(--stellar-card)',
        'card-foreground': 'var(--stellar-card-foreground)',
        popover: 'var(--stellar-popover)',
        'popover-foreground': 'var(--stellar-popover-foreground)',
        border: 'var(--stellar-border)',
        input: 'var(--stellar-input)',
        ring: 'var(--stellar-ring)',
      },
    },
    borderRadius: {
      stellar: 'var(--stellar-radius)', // ${borderRadius}
    },
  },
}

export default ${themeName}Theme
`
}

// Default palette for --yes / backward compat
const DEFAULT_PALETTE: ThemePalette = {
  primary: '#667eea',
  secondary: '#e2e8f0',
  accent: '#764ba2',
  background: '#ffffff',
  foreground: '#1a1a2e',
}

async function themeCreateAction(options: { yes?: boolean, cwd?: string }): Promise<void> {
  const cwd = path.resolve(options.cwd ?? process.cwd())

  header('Stellar UI - Create Custom Theme')

  let themeName: string
  let palette: ThemePalette
  let borderRadius: string

  if (options.yes) {
    themeName = 'my-theme'
    palette = DEFAULT_PALETTE
    borderRadius = '0.5rem'
  }
  else {
    const response = await prompts([
      {
        type: 'text',
        name: 'themeName',
        message: 'Theme name',
        initial: 'my-theme',
        validate: (value: string) => (value.trim().length > 0 ? true : 'Theme name is required'),
      },
      {
        type: 'select',
        name: 'themeType',
        message: 'Theme type',
        choices: [
          { title: 'Light', value: 'light' },
          { title: 'Dark', value: 'dark' },
        ],
        initial: 0,
      },
      {
        type: 'text',
        name: 'primary',
        message: 'Primary color (hex)',
        initial: '#667eea',
        validate: validateHex,
      },
      {
        type: 'text',
        name: 'secondary',
        message: 'Secondary color (hex)',
        initial: '#e2e8f0',
        validate: validateHex,
      },
      {
        type: 'text',
        name: 'accent',
        message: 'Accent color (hex)',
        initial: '#764ba2',
        validate: validateHex,
      },
      {
        type: 'text',
        name: 'background',
        message: 'Background color (hex)',
        initial: '#ffffff',
        validate: validateHex,
      },
      {
        type: 'text',
        name: 'foreground',
        message: 'Foreground color (hex)',
        initial: '#1a1a2e',
        validate: validateHex,
      },
      {
        type: 'select',
        name: 'borderRadius',
        message: 'Border radius',
        choices: BORDER_RADIUS_OPTIONS,
        initial: 3, // lg = 0.5rem
      },
    ])

    if (response.themeName === undefined) {
      console.log(styles.info('Theme creation cancelled.'))
      return
    }

    themeName = response.themeName as string
    palette = {
      primary: (response.primary as string) || DEFAULT_PALETTE.primary,
      secondary: (response.secondary as string) || DEFAULT_PALETTE.secondary,
      accent: (response.accent as string) || DEFAULT_PALETTE.accent,
      background: (response.background as string) || DEFAULT_PALETTE.background,
      foreground: (response.foreground as string) || DEFAULT_PALETTE.foreground,
    }
    borderRadius = (response.borderRadius as string) ?? '0.5rem'
  }

  const cssContent = generateThemeCss(themeName, palette, borderRadius)

  const themesDir = path.join(cwd, 'themes')
  if (!fs.existsSync(themesDir)) {
    fs.mkdirSync(themesDir, { recursive: true })
  }

  const themeFile = path.join(themesDir, `${themeName}.css`)
  fs.writeFileSync(themeFile, cssContent, 'utf-8')

  newLine()
  console.log(styles.success(`Theme "${themeName}" created at themes/${themeName}.css`))
  console.log(styles.dim(`  Primary: ${palette.primary}`))
  console.log(styles.dim(`  Secondary: ${palette.secondary}`))
  console.log(styles.dim(`  Accent: ${palette.accent}`))
  console.log(styles.dim(`  Border radius: ${borderRadius}`))
  newLine()
}

async function themeListAction(): Promise<void> {
  header('Stellar UI - Available Themes')

  console.log(styles.highlight('Built-in themes:'))
  newLine()

  for (const theme of BUILT_IN_THEMES) {
    console.log(`  ${styles.title(theme.name.padEnd(14))} ${styles.dim(theme.description)}`)
  }

  // Check for custom themes in the project
  const cwd = process.cwd()
  const themesDir = path.join(cwd, 'themes')

  if (fs.existsSync(themesDir)) {
    const files = fs.readdirSync(themesDir).filter(f => f.endsWith('.css'))
    if (files.length > 0) {
      newLine()
      console.log(styles.highlight('Custom themes:'))
      newLine()
      for (const file of files) {
        const name = file.replace(/\.css$/, '')
        console.log(`  ${styles.title(name.padEnd(14))} ${styles.dim('Custom theme')}`)
      }
    }
  }

  newLine()
}

async function themeApplyAction(name: string, options: { cwd?: string }): Promise<void> {
  const cwd = path.resolve(options.cwd ?? process.cwd())

  const config = await readConfig(cwd)
  if (!config) {
    console.log(styles.error('No Stellar UI config found. Run `stellar-ui init` first.'))
    process.exitCode = 1
    return
  }

  // Validate the theme name
  const builtInNames = BUILT_IN_THEMES.map(t => t.name)
  const themesDir = path.join(cwd, 'themes')
  const customThemes: string[] = fs.existsSync(themesDir)
    ? fs
        .readdirSync(themesDir)
        .filter(f => f.endsWith('.css'))
        .map(f => f.replace(/\.css$/, ''))
    : []

  const allThemes = [...builtInNames, ...customThemes]
  if (!allThemes.includes(name)) {
    console.log(styles.error(`Unknown theme: "${name}". Available themes: ${allThemes.join(', ')}`))
    process.exitCode = 1
    return
  }

  // Write theme CSS to the variables file
  const cssPath = path.join(cwd, config.cssVariables)
  const isBuiltIn = (builtInNames as string[]).includes(name)

  if (isBuiltIn) {
    const themeCSS = THEME_TEMPLATES[name]
    if (!themeCSS) {
      console.log(styles.error(`Theme template "${name}" not found.`))
      process.exitCode = 1
      return
    }
    const cssDir = path.dirname(cssPath)
    if (!fs.existsSync(cssDir)) {
      fs.mkdirSync(cssDir, { recursive: true })
    }
    fs.writeFileSync(cssPath, themeCSS, 'utf-8')
  }
  else {
    // Custom theme — copy from themes/ directory
    const customCssPath = path.join(themesDir, `${name}.css`)
    const cssDir = path.dirname(cssPath)
    if (!fs.existsSync(cssDir)) {
      fs.mkdirSync(cssDir, { recursive: true })
    }
    fs.copyFileSync(customCssPath, cssPath)
  }

  // Update config with the new theme reference
  const updatedConfig = {
    ...config,
    theme: name,
  } as typeof config & { theme: string }

  const configDir = await findConfig(cwd)
  if (!configDir) {
    console.log(styles.error('Could not find config directory.'))
    process.exitCode = 1
    return
  }

  await writeConfig(updatedConfig as typeof config, configDir)

  console.log(styles.success(`Theme "${name}" applied to your project.`))
  console.log(styles.dim(`  CSS variables written to ${config.cssVariables}`))
  newLine()
}

async function themeExportAction(name: string, options: { format?: string }): Promise<void> {
  const format = options.format ?? 'css'

  // Validate format
  if (!['css', 'json', 'tailwind'].includes(format)) {
    console.log(styles.error(`Unknown format: "${format}". Use: css, json, or tailwind`))
    process.exitCode = 1
    return
  }

  // Find theme data
  const builtInTheme = BUILT_IN_THEMES.find(t => t.name === name)
  if (!builtInTheme) {
    // Check for custom theme file
    const cwd = process.cwd()
    const themeFile = path.join(cwd, 'themes', `${name}.css`)
    if (!fs.existsSync(themeFile)) {
      console.log(
        styles.error(
          `Unknown theme: "${name}". Use \`stellar-ui theme list\` to see available themes.`,
        ),
      )
      process.exitCode = 1
      return
    }
    // For custom themes, just output the CSS file content for css format
    if (format === 'css') {
      console.log(fs.readFileSync(themeFile, 'utf-8'))
      return
    }
  }

  const borderRadius = '0.5rem'

  let output: string

  switch (format) {
    case 'json':
      output = generateThemeJson(name, DEFAULT_PALETTE, borderRadius)
      break
    case 'tailwind':
      output = generateThemeTailwind(name, borderRadius)
      break
    case 'css':
    default:
      output = generateThemeCss(name, DEFAULT_PALETTE, borderRadius)
      break
  }

  console.log(output)
}

export function registerThemeCommand(program: Command): void {
  const theme = program.command('theme').description('Manage themes')

  theme
    .command('create')
    .description('Create a custom theme')
    .option('-y, --yes', 'Use defaults')
    .option('--cwd <cwd>', 'Working directory', process.cwd())
    .action(themeCreateAction)

  theme.command('list').description('List available themes').action(themeListAction)

  theme
    .command('apply <name>')
    .description('Apply a theme to your project')
    .option('--cwd <cwd>', 'Working directory', process.cwd())
    .action(themeApplyAction)

  theme
    .command('export <name>')
    .description('Export a theme')
    .option('-f, --format <format>', 'Output format: css, json, or tailwind', 'css')
    .action(themeExportAction)
}
