import type { ComponentLock } from '../types'
import fs from 'node:fs'
import path from 'node:path'
import prompts from 'prompts'
import { findConfig, readConfig, readLockFile, writeLockFile } from '../utils/config'
import { computeHash, displayDiff } from '../utils/diff'
import { newLine, styles } from '../utils/prompts'
import { getComponent } from '../utils/registry'

interface UpdateOptions {
  cwd?: string
  all?: boolean
  yes?: boolean
}

/**
 * Update one or more installed components.
 */
export async function updateCommand(components: string[], options: UpdateOptions): Promise<void> {
  const cwd = path.resolve(options.cwd ?? process.cwd())

  // 1. Read config and lock file — error if not initialized
  const configDir = await findConfig(cwd)
  if (!configDir) {
    console.error(styles.error('Stellar UI is not initialized. Run `stellar-ui init` first.'))
    process.exitCode = 1
    return
  }

  const config = await readConfig(cwd)
  if (!config) {
    console.error(styles.error('Failed to read Stellar UI config. Run `stellar-ui init` first.'))
    process.exitCode = 1
    return
  }

  const lock: ComponentLock | null = await readLockFile(cwd)
  if (!lock) {
    console.error(styles.error('No lock file found. Run `stellar-ui init` first.'))
    process.exitCode = 1
    return
  }

  // 2. Determine which components to update
  let componentNames: string[]
  if (options.all) {
    componentNames = Object.keys(lock.components)
    if (componentNames.length === 0) {
      console.log(styles.info('No components installed.'))
      return
    }
  }
  else {
    componentNames = [...components]
    if (componentNames.length === 0) {
      console.log(styles.info('No components specified. Use --all to update all installed components.'))
      return
    }
  }

  const updatedComponents: string[] = []
  const skippedComponents: string[] = []

  // 3. For each component
  for (const name of componentNames) {
    // a. Check it's in the lock file
    const lockEntry = lock.components[name]
    if (!lockEntry) {
      console.error(styles.error(`Component "${name}" is not installed.`))
      process.exitCode = 1
      return
    }

    // b. Compare installed version with registry version
    const registryEntry = getComponent(name)
    if (!registryEntry) {
      console.error(styles.error(`Component "${name}" not found in registry.`))
      process.exitCode = 1
      return
    }

    // c. If same version, skip
    if (lockEntry.version === registryEntry.version) {
      console.log(styles.dim(`"${name}" is already up to date (v${lockEntry.version}).`))
      skippedComponents.push(name)
      continue
    }

    // d. Check for customization
    const componentDir = path.join(cwd, config.componentsDir, name)
    let hasCustomizations = false

    if (fs.existsSync(componentDir)) {
      for (const file of lockEntry.files) {
        const filePath = path.join(cwd, file)
        if (fs.existsSync(filePath)) {
          const currentContent = fs.readFileSync(filePath, 'utf-8')
          const originalContent = `// Generated by stellar-ui CLI - component: ${name}\n// File: ${path.basename(file)}\n`
          if (computeHash(currentContent) !== computeHash(originalContent)) {
            hasCustomizations = true
            break
          }
        }
      }
    }

    if (hasCustomizations && !options.yes) {
      console.log(styles.warning(`Component "${name}" has been customized.`))

      // e. Show diff preview
      for (const file of lockEntry.files) {
        const filePath = path.join(cwd, file)
        if (fs.existsSync(filePath)) {
          const currentContent = fs.readFileSync(filePath, 'utf-8')
          const newContent = `// Generated by stellar-ui CLI - component: ${name}\n// File: ${path.basename(file)}\n// Updated to version ${registryEntry.version}\n`
          displayDiff(path.basename(file), currentContent, newContent)
        }
      }

      const { confirm } = await prompts({
        type: 'confirm',
        name: 'confirm',
        message: `Update "${name}" and overwrite customizations?`,
        initial: false,
      })

      if (!confirm) {
        console.log(styles.dim(`Skipping "${name}".`))
        continue
      }
    }

    // f. Apply update (write new files)
    if (!fs.existsSync(componentDir)) {
      fs.mkdirSync(componentDir, { recursive: true })
    }

    const writtenFiles: string[] = []
    for (const file of registryEntry.files) {
      const fileName = path.basename(file)
      const filePath = path.join(componentDir, fileName)
      const content = `// Generated by stellar-ui CLI - component: ${name}\n// File: ${file}\n// Updated to version ${registryEntry.version}\n`
      fs.writeFileSync(filePath, content, 'utf-8')
      writtenFiles.push(path.join(config.componentsDir, name, fileName))
    }

    // g. Update lock file entry
    lock.components[name] = {
      version: registryEntry.version,
      installedAt: new Date().toISOString(),
      customized: false,
      files: writtenFiles,
      dependencies: { ...registryEntry.dependencies },
    }

    updatedComponents.push(name)
  }

  // Write updated lock file
  await writeLockFile(lock, configDir)

  // 4. Show summary
  newLine()
  if (updatedComponents.length > 0) {
    console.log(styles.success(`Updated ${updatedComponents.length} component(s): ${updatedComponents.join(', ')}`))
  }
  if (skippedComponents.length > 0) {
    console.log(styles.dim(`${skippedComponents.length} component(s) already up to date.`))
  }
  if (updatedComponents.length === 0 && skippedComponents.length === 0) {
    console.log(styles.info('No components were updated.'))
  }
}
