import type { ComponentLock } from '../types'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { defineConfig } from '../types'
import { writeConfig, writeLockFile } from '../utils/config'

import { updateCommand } from './update'

// Mock prompts module
vi.mock('prompts', () => ({
  default: vi.fn(),
}))

describe('update command', () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'stellar-cli-update-test-'))
    vi.clearAllMocks()
    vi.spyOn(console, 'log').mockImplementation(() => {})
    vi.spyOn(console, 'error').mockImplementation(() => {})
    process.exitCode = undefined
  })

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
    vi.restoreAllMocks()
    process.exitCode = undefined
  })

  async function initProjectWithComponent(
    dir: string,
    componentName: string,
    version: string,
  ): Promise<void> {
    const config = defineConfig({})
    await writeConfig(config, dir)

    // Create component files with stub content (simulating old update behavior)
    const componentDir = path.join(dir, config.componentsDir, componentName)
    fs.mkdirSync(componentDir, { recursive: true })

    const fileName = `${componentName.charAt(0).toUpperCase() + componentName.slice(1)}.vue`
    const filePath = path.join(componentDir, fileName)
    const content = `// Generated by stellar-ui CLI - component: ${componentName}\n// File: ${fileName}\n`
    fs.writeFileSync(filePath, content, 'utf-8')

    const lock: ComponentLock = {
      version: '1.0.0',
      components: {
        [componentName]: {
          version,
          installedAt: new Date().toISOString(),
          customized: false,
          files: [path.join(config.componentsDir, componentName, fileName)],
          dependencies: {},
        },
      },
    }
    await writeLockFile(lock, dir)
  }

  it('detects up-to-date components (same version)', async () => {
    // Button in registry is version 0.1.0
    await initProjectWithComponent(tmpDir, 'button', '0.1.0')

    await updateCommand(['button'], { cwd: tmpDir })

    // Should not have errored
    expect(process.exitCode).toBeUndefined()

    // Lock file version should still be the same
    const lockPath = path.join(tmpDir, 'components.lock.json')
    const lock = JSON.parse(fs.readFileSync(lockPath, 'utf-8')) as ComponentLock
    expect(lock.components.button!.version).toBe('0.1.0')
  })

  it('updates lock file version after update', async () => {
    // Install with an older version so it triggers an update
    await initProjectWithComponent(tmpDir, 'button', '0.0.1')

    await updateCommand(['button'], { cwd: tmpDir, yes: true })

    const lockPath = path.join(tmpDir, 'components.lock.json')
    const lock = JSON.parse(fs.readFileSync(lockPath, 'utf-8')) as ComponentLock
    expect(lock.components.button!.version).toBe('0.1.0')
  })

  it('writes real template content, not stubs', async () => {
    await initProjectWithComponent(tmpDir, 'button', '0.0.1')

    await updateCommand(['button'], { cwd: tmpDir, yes: true })

    const config = defineConfig({})
    // Check that at least one file has real template content
    const buttonDir = path.join(tmpDir, config.componentsDir, 'button')
    const files = fs.readdirSync(buttonDir)
    expect(files.length).toBeGreaterThan(0)

    // Verify content is not a stub
    for (const file of files) {
      const content = fs.readFileSync(path.join(buttonDir, file), 'utf-8')
      // Real templates should have actual component code, not just comment stubs
      expect(content).not.toMatch(
        /^\/\/ Generated by stellar-ui CLI - component:.*\n\/\/ File:.*\n$/,
      )
    }
  })

  it('--force updates even when version matches', async () => {
    await initProjectWithComponent(tmpDir, 'button', '0.1.0')

    await updateCommand(['button'], { cwd: tmpDir, force: true, yes: true })

    expect(process.exitCode).toBeUndefined()

    const lockPath = path.join(tmpDir, 'components.lock.json')
    const lock = JSON.parse(fs.readFileSync(lockPath, 'utf-8')) as ComponentLock
    expect(lock.components.button!.version).toBe('0.1.0')

    // Verify the component was actually rewritten with template content
    const config = defineConfig({})
    const buttonDir = path.join(tmpDir, config.componentsDir, 'button')
    const files = fs.readdirSync(buttonDir)
    for (const file of files) {
      const content = fs.readFileSync(path.join(buttonDir, file), 'utf-8')
      expect(content).not.toMatch(
        /^\/\/ Generated by stellar-ui CLI - component:.*\n\/\/ File:.*\n$/,
      )
    }
  })

  it('--all flag updates all installed components', async () => {
    const config = defineConfig({})
    await writeConfig(config, tmpDir)

    // Create two components with old versions
    const lock: ComponentLock = {
      version: '1.0.0',
      components: {
        button: {
          version: '0.0.1',
          installedAt: new Date().toISOString(),
          customized: false,
          files: [path.join(config.componentsDir, 'button', 'Button.vue')],
          dependencies: {},
        },
        card: {
          version: '0.0.1',
          installedAt: new Date().toISOString(),
          customized: false,
          files: [path.join(config.componentsDir, 'card', 'Card.vue')],
          dependencies: {},
        },
      },
    }
    await writeLockFile(lock, tmpDir)

    // Create component directories
    for (const name of ['button', 'card']) {
      const componentDir = path.join(tmpDir, config.componentsDir, name)
      fs.mkdirSync(componentDir, { recursive: true })
      const fileName = name === 'button' ? 'Button.vue' : 'Card.vue'
      fs.writeFileSync(
        path.join(componentDir, fileName),
        `// Generated by stellar-ui CLI - component: ${name}\n// File: ${fileName}\n`,
        'utf-8',
      )
    }

    await updateCommand([], { cwd: tmpDir, all: true, yes: true })

    const lockPath = path.join(tmpDir, 'components.lock.json')
    const updatedLock = JSON.parse(fs.readFileSync(lockPath, 'utf-8')) as ComponentLock
    expect(updatedLock.components.button!.version).toBe('0.1.0')
    expect(updatedLock.components.card!.version).toBe('0.1.0')
  })

  it('--all --force updates all even at same version', async () => {
    const config = defineConfig({})
    await writeConfig(config, tmpDir)

    const lock: ComponentLock = {
      version: '1.0.0',
      components: {
        button: {
          version: '0.1.0',
          installedAt: new Date().toISOString(),
          customized: false,
          files: [path.join(config.componentsDir, 'button', 'Button.vue')],
          dependencies: {},
        },
      },
    }
    await writeLockFile(lock, tmpDir)

    const componentDir = path.join(tmpDir, config.componentsDir, 'button')
    fs.mkdirSync(componentDir, { recursive: true })
    fs.writeFileSync(path.join(componentDir, 'Button.vue'), `// stub\n`, 'utf-8')

    await updateCommand([], { cwd: tmpDir, all: true, force: true, yes: true })

    // Should have updated despite same version
    const buttonDir = path.join(tmpDir, config.componentsDir, 'button')
    const files = fs.readdirSync(buttonDir)
    for (const file of files) {
      const content = fs.readFileSync(path.join(buttonDir, file), 'utf-8')
      expect(content).not.toBe('// stub\n')
    }
  })

  it('errors when component not installed', async () => {
    const config = defineConfig({})
    await writeConfig(config, tmpDir)
    await writeLockFile({ version: '1.0.0', components: {} }, tmpDir)

    await updateCommand(['button'], { cwd: tmpDir })

    expect(process.exitCode).toBe(1)
  })

  it('errors when config not initialized', async () => {
    await updateCommand(['button'], { cwd: tmpDir })

    expect(process.exitCode).toBe(1)
  })
})
