// Auto-generated by scripts/generate-templates.ts — DO NOT EDIT
export const UTIL_TEMPLATES: Record<string, string> = {
  'cn.ts':
    'import { type ClassValue, clsx } from \'clsx\'\nimport { twMerge } from \'tailwind-merge\'\n\n/**\n * Merges CSS classes using clsx and tailwind-merge\n *\n * Combines multiple class values, handles conditional classes,\n * and resolves Tailwind CSS conflicts.\n *\n * @param inputs - Class values to merge\n * @returns Merged class string with Tailwind conflicts resolved\n *\n * @example\n * ```ts\n * cn(\'px-4 py-2\', \'px-6\') // \'px-6 py-2\'\n * cn(\'text-red-500\', someCondition && \'text-blue-500\')\n * cn(\'bg-primary\', props.class)\n * ```\n */\nexport function cn(...inputs: ClassValue[]): string {\n  return twMerge(clsx(inputs))\n}\n',
  'index.ts': 'export { cn } from \'./cn\'\nexport { cva, type VariantProps } from \'./variants\'\n',
  'variants.ts': 'export { cva, type VariantProps } from \'class-variance-authority\'\n',
}
