export type { AvatarFallbackProps, AvatarImageProps, AvatarProps } from './avatar.types'
export { avatarVariants, type AvatarVariants } from './avatar.variants'
export { default as Avatar } from './Avatar.vue'
export { default as AvatarFallback } from './AvatarFallback.vue'
export { default as AvatarImage } from './AvatarImage.vue'
