/**
 * Build-time script that reads component source files from packages/core
 * and generates embedded template modules for the CLI.
 *
 * Usage: tsx scripts/generate-templates.ts
 */
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(__dirname, '../../..')
const CORE_COMPONENTS = path.join(ROOT, 'packages/core/src/components')
const CORE_UTILS = path.join(ROOT, 'packages/core/src/utils')
const OUT_DIR = path.join(ROOT, 'packages/cli/src/templates')

function isSourceFile(file: string): boolean {
  if (file.endsWith('.test.ts') || file.endsWith('.spec.ts'))
    return false
  if (file.endsWith('.test.vue') || file.endsWith('.spec.vue'))
    return false
  return file.endsWith('.ts') || file.endsWith('.vue')
}

function generateComponentTemplates(): void {
  const componentDirs = fs
    .readdirSync(CORE_COMPONENTS, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort()

  const entries: string[] = []

  for (const componentName of componentDirs) {
    const componentDir = path.join(CORE_COMPONENTS, componentName)
    const files = fs.readdirSync(componentDir).filter(isSourceFile).sort()

    if (files.length === 0)
      continue

    const fileEntries: string[] = []
    for (const file of files) {
      const content = fs.readFileSync(path.join(componentDir, file), 'utf-8')
      fileEntries.push(`    ${JSON.stringify(file)}: ${JSON.stringify(content)}`)
    }

    entries.push(`  ${JSON.stringify(componentName)}: {\n${fileEntries.join(',\n')}\n  }`)
  }

  const output = `/* eslint-disable no-template-curly-in-string */
// Auto-generated by scripts/generate-templates.ts — DO NOT EDIT
export const COMPONENT_TEMPLATES: Record<string, Record<string, string>> = {
${entries.join(',\n')}
}
`

  fs.writeFileSync(path.join(OUT_DIR, 'components.ts'), output, 'utf-8')
  console.log(`Generated templates for ${entries.length} components`)
}

function generateUtilTemplates(): void {
  const utilFiles = fs.readdirSync(CORE_UTILS).filter(isSourceFile).sort()

  const fileEntries: string[] = []
  for (const file of utilFiles) {
    const content = fs.readFileSync(path.join(CORE_UTILS, file), 'utf-8')
    fileEntries.push(`  ${JSON.stringify(file)}: ${JSON.stringify(content)}`)
  }

  const output = `/* eslint-disable no-template-curly-in-string */
// Auto-generated by scripts/generate-templates.ts — DO NOT EDIT
export const UTIL_TEMPLATES: Record<string, string> = {
${fileEntries.join(',\n')}
}
`

  fs.writeFileSync(path.join(OUT_DIR, 'utils.ts'), output, 'utf-8')
  console.log(`Generated templates for ${utilFiles.length} util files`)
}

// Ensure output directory exists
if (!fs.existsSync(OUT_DIR)) {
  fs.mkdirSync(OUT_DIR, { recursive: true })
}

generateComponentTemplates()
generateUtilTemplates()
