/**
 * Build-time script that generates embedded theme CSS templates for the CLI.
 *
 * For each theme in packages/theme, it:
 *   1. Runs generateCSS() to produce the @theme block (light mode tokens)
 *   2. Appends the shared dark mode overrides, keyframes, and @utility blocks from app.css
 *
 * Output: packages/cli/src/templates/themes.ts
 *
 * Usage: tsx scripts/generate-theme-templates.ts
 */
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(__dirname, '../../..')
const THEME_PKG = path.join(ROOT, 'packages/theme')
const APP_CSS = path.join(ROOT, 'packages/core/src/assets/app.css')
const OUT_DIR = path.join(ROOT, 'packages/cli/src/templates')

async function main(): Promise<void> {
  // Dynamically import the theme package (it uses TypeScript, so we rely on tsx)
  const { themes } = await import(path.join(THEME_PKG, 'src/themes/index.ts'))
  const { generateCSS } = await import(path.join(THEME_PKG, 'src/generator/css-generator.ts'))

  // Read app.css to extract dark mode, keyframes, and @utility blocks
  const appCss = fs.readFileSync(APP_CSS, 'utf-8')

  // Extract everything after the @theme { ... } block (dark mode, keyframes, utilities)
  // The @theme block ends with a closing brace followed by the dark mode section comment
  const themeBlockEnd = appCss.indexOf('\n\n/* =')
  if (themeBlockEnd === -1) {
    throw new Error('Could not find end of @theme block in app.css')
  }
  const sharedSuffix = appCss.slice(themeBlockEnd).trim()

  // Build the templates map
  const entries: string[] = []

  for (const theme of themes) {
    const themeBlock = generateCSS(theme)
    const css = [
      `/* Stellar UI - Theme: ${theme.name.charAt(0).toUpperCase() + theme.name.slice(1)} */`,
      `/* Generated by @stellar-vue-ui/cli */`,
      '',
      themeBlock,
      '',
      sharedSuffix,
      '',
    ].join('\n')

    entries.push(`  ${JSON.stringify(theme.name)}: ${JSON.stringify(css)}`)
  }

  const output = `// Auto-generated by scripts/generate-theme-templates.ts — DO NOT EDIT
export const THEME_TEMPLATES: Record<string, string> = {
${entries.join(',\n')}
}
`

  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true })
  }

  fs.writeFileSync(path.join(OUT_DIR, 'themes.ts'), output, 'utf-8')
  console.log(`Generated theme templates for ${entries.length} themes`)
}

main().catch((err) => {
  console.error('Failed to generate theme templates:', err)
  process.exit(1)
})
